---
- name: Install and start services based on group vars
  hosts: pd_app:pd_database
  #hosts: web
  #hosts:db
  tasks:
    - name: Install required package
      apt:
        name: "{{ pkg_name }}"
        state: present
        update_cache: yes
 
    - name: Start and enable the service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
 
    - name: Print role info
      debug:
        msg: "This host is configured as a {{ role }}"
