---
- hosts: web
  tasks:
  - name: create directory
    file:
      path: "/home/ubuntu/test1"
      state: directory
  - name: create a user 
    user:
      name: testuser
      shell: /bin/bash
      uid: 1100
      comment: "my first user "
      state: present
