---
- name: Secure Automation with Ansible Vault on Ubuntu
  hosts: app:db
  become: true
  gather_facts: true

  vars_files:
    - vault.yml

  tasks:
    - name: Debug current host and group
      debug:
        msg: "Running on host {{ inventory_hostname }} in group {{ group_names }}"

    # - name: Show Encrypted Web Password (web group only)
    #   debug:
    #     var: vault_password.application
    #   when: "'app' in group_names"

    # - name: Show Encrypted DB Password (db group only)
    #   debug:
    #     var: vault_password.database
    #   when: "'db' in group_names"

    - name: Ensure required packages are installed
      apt:
        name: "{{ pkg }}"
        state: present
        update_cache: yes
      when: pkg is defined

    - name: Create a user with vault password
      user:
        name: appuser1
        password: "{{ vault_password.database }}"
        shell: /bin/bash
        state: present

    - name: Create application configuration file with credentials
      copy:
        dest: "/etc/app_secure.conf"
        content: |
          [credentials]
          user = appuser1
          password = {{ vault_password.database }}
        owner: root
        group: root
        mode: '0600'

    - name: Ensure the application service is running (apache2 or mysql)
      service:
        name: "{{ 'apache2' if 'app' in group_names else 'mysql' }}"
        state: started
        enabled: true