---
- hosts: app
  vars_files:
    - vault.yml
  tasks:
    - name: Show encrypted application password
      debug:
        var: vault_password.application 
    - name: Show encrypted db password
      debug:
        var: vault_password.database
  # - name: create directory
  #   file:
  #     path: "/home/ec2-user/test"
  #     state: directory
  # - name: create a user 
  #   user:
  #     name: testuser
  #     shell: /bin/bash
  #     uid: 1100
  #     comment: "my first user "
  #     state: present
