---
- hosts: app
  tasks:
  - name: create directory
    file:
      path: "/home/ubuntu/test"
      state: directory
  - name: create a user 
    user:
      name: testuser2
      shell: /bin/bash
      uid: 1103
      comment: "my first user "
      state: present
