---
- hosts: pd_app:pd_database
  tasks:
  - name: create directory
    file:
      path: "{{ dir_path}}"
      state: "{{ dir_state }}"
  - name: create a user 
    user:
      name: testuser
      shell: /bin/bash
      uid: 1100
      comment: "my first user "
      state: "{{ user_state }}"
